import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link';
import styles from '@/styles/Home.module.css'
import yugi_img from '../../public/yugi.png'

const inter = Inter({ subsets: ['latin'] })

const button_style = "btn text-light mt-5 py-2 px-3 rounded-5 fs-5 border-0 w-50";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
          <div className='w-75 text-light pt-4 d-flex ps-5 justify-content-between rounded-5' style={{backgroundColor:'rgba(1,1,1, 0.7)'}}>
              
              <div>
                <h3 className='ms-5 mt-5' > Welcome to Yugioh Cards Website! </h3> 
                <h4 className='ms-5 mt-5' > Easily navigate and preview cards </h4>
                <Link href={"/cards"} className={button_style} style={{backgroundColor:'saddlebrown'}}>Check Cards</Link>
              </div>
 
              <Image src={yugi_img} width="250" height="450"></Image>
          </div>
      </main>
    </>
  )
}
